services:
  mcc-backend:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: mcc-backend
    image: local/mcc-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - infra/.env
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:6.2-alpine
    container_name: mcc-redis
